my-free-time:
  config:
    checkin-before-h: 9
    checkin-before-m: 0
    checkout-after-h: 18
    checkout-after-m: 55
    checkin: "false"
    checkout: "true"
    max-variant: 15

quarkus:
  package:
    type: uber-jar
    add-runner-suffix: false
  http:
    port: 22112
  rest-client:
    mytime:
      uri: ${mytime_ws_url}
