my-free-time:
  config:
    checkin-before-h: 9
    checkin-before-m: 0
    checkout-after-h: 18
    checkout-after-m: 55
    checkin: "false"
    checkout: "true"
    max-variant: 15

quarkus:
  package:
    type: uber-jar
    add-runner-suffix: false
  http:
    port: 22112
  rest-client:
    mytime:
      uri: ${mytime_ws_url}
  mailer:
    auth-methods: DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
    from: ${mailer_email}
    host: smtp.gmail.com
    port: 587
    start-tls: required
    username: ${mailer_email}
    password: ${mailer_pw}
    mock: false